#! /bin/bash
zip -q -T Projecto4_v21.0.zip mccompiler.l mccompiler.y ast.c ast.h simbtab.c simbtab.h ast_to_llvm.c ast_to_llvm.h makefile
zip -q -T mccompiler.zip mccompiler.l mccompiler.y ast.c ast.h simbtab.c simbtab.h ast_to_llvm.c ast_to_llvm.h
